highlighter: rouge
markdown: kramdown
timezone: Europe/Zurich
title: Slim Twig-View
include: [.htaccess]
exclude: [.idea, _includes, _js, _layouts, _scss, node_modules, Gemfile, Gemfile.lock, Gruntfile.js, LICENSE, package.json, package-lock.json, README.md]
baseurl: /Slim-Twig-View-Website

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      docs-v3:
        - title: Get Started
          items:
            - [/docs/v3, Home]
            - [/docs/v3/start/installation.md, Installation]
            - [/docs/v3/start/configuration.md, Configuration]
        - title: Without Container
          items:
            - [/docs/v3/without-container/hello-world.md, Hello World]
        - title: With Container
          items:
            - [/docs/v3/with-container/hello-world.md, Hello World]

  - scope:
      path: "docs/v3"
      type: "pages"
    values:
      layout: docs-v3
